# Generated by Django 6.0 on 2026-01-06 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_alter_filme_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='thumb_filmes')),
                ('descricao', models.TextField(max_length=1000)),
                ('categoria', models.CharField(choices=[('AULA', 'Aula'), ('PROGRAMACAO', 'Programação'), ('CURSOS', 'Outros'), ('OUTROS', 'Outros'), ('TERRORPSI', 'Terror Psicológico')], max_length=20)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('lancamento', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='filme',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
    ]
